/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.astaxdev.cardapio.view;

import com.astaxdev.cardapio.model.TipoUsuario;
import com.astaxdev.cardapio.model.Usuario;
import com.astaxdev.cardapio.util.BancoDeDados;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class Cadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastro.class.getName());
    private BancoDeDados banco = BancoDeDados.getInstance();
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        txtNomeCad = new javax.swing.JTextField();
        labNome = new javax.swing.JLabel();
        labSenha = new javax.swing.JLabel();
        btnCad = new javax.swing.JButton();
        pswSenha = new javax.swing.JPasswordField();
        pswSenha1 = new javax.swing.JPasswordField();
        labSenha1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labAviso = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(txtNomeCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 115, 240, -1));

        labNome.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labNome.setText("Nome:");
        jPanel9.add(labNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 118, -1, -1));

        labSenha.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labSenha.setText("Senha:");
        jPanel9.add(labSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 149, -1, -1));

        btnCad.setBackground(new java.awt.Color(102, 10, 23));
        btnCad.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnCad.setForeground(new java.awt.Color(255, 255, 255));
        btnCad.setText("Cadastrar");
        btnCad.addActionListener(this::btnCadActionPerformed);
        jPanel9.add(btnCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));
        jPanel9.add(pswSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 146, 240, -1));

        pswSenha1.addActionListener(this::pswSenha1ActionPerformed);
        jPanel9.add(pswSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 177, 240, -1));

        labSenha1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        labSenha1.setText("Confirmar Senha:");
        jPanel9.add(labSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 10, 23));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/man,guy,person,stool,bar,laptop,computer,earbuds,furniture.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 290));

        labAviso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel9.add(labAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 380, 37));

        jLabel3.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fazer cadastro");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
      
        if(validarCampos()){
            banco.getUsuarios().add(retornaCadastro());
            limparCampos();
            this.dispose();
            new Login().setVisible(true);
        }

    }//GEN-LAST:event_btnCadActionPerformed

    private void pswSenha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswSenha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswSenha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labAviso;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labSenha;
    private javax.swing.JLabel labSenha1;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JPasswordField pswSenha1;
    private javax.swing.JTextField txtNomeCad;
    // End of variables declaration//GEN-END:variables
    
    private boolean validarCampos(){
        String username, senha, confirmarSenha;
        username =txtNomeCad.getText();
        senha = new String(pswSenha.getPassword());
        confirmarSenha = new String(pswSenha1.getPassword());
        
        if(username.equals("") || senha.equals("") || confirmarSenha.equals("")){
            labAviso.setText("Preencha todos os campos");
            return false;
            
        }else if(senha.equals(confirmarSenha)){
            labAviso.setText("Usuario cadastrado");
           
            return true;
        }else{
            labAviso.setText("Senhas não coincidem");
            return false;
        }
        
    }
    
    private void limparCampos(){
        txtNomeCad.setText("");
        pswSenha.setText("");
        pswSenha1.setText("");
        
    }
    
    private Usuario retornaCadastro(){
        String username, senha;
        username = txtNomeCad.getText();
        senha = new String(pswSenha.getPassword());    
        
        
        return new Usuario(username, senha, TipoUsuario.PADRAO);
        
    }
}
