/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.astaxdev.cardapio.view;

import com.astaxdev.cardapio.view.cardapio.TelaCardapio;
import com.astaxdev.cardapio.view.gerenciamento.TelaGerenciamento;
import com.astaxdev.cardapio.view.gerenciamento.TelaPerfil;
import com.astaxdev.cardapio.view.principal.TelaPrincipal;
import java.awt.CardLayout;

/**
 *
 * @author astaxgg
 */

public class Main extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());
    private CardLayout card;

    /**
     * Creates new form MainView
     */
    public Main() {
        initComponents();
        
        setLocationRelativeTo(this);
        
        card = new CardLayout();
        pnlRightSide.setLayout(card);
        pnlRightSide.add(new TelaPrincipal(), "Principal");
        pnlRightSide.add(new TelaCardapio(), "Cardapio");
        pnlRightSide.add(new TelaGerenciamento(), "Gerenciamento");
        pnlRightSide.add(new TelaPerfil(), "Perfil");
        card.show(pnlRightSide, "Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Background = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        labSair = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JSplitPane();
        pnlLeftSide = new javax.swing.JPanel();
        btnCardapio = new javax.swing.JButton();
        btnGerenciamento = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        pnlRightSide = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(123, 16, 32));

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setText("Sistema de Cardapio");

        lblSubtitulo.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        lblSubtitulo.setText("Gerencie seu cardapio");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante-48.png"))); // NOI18N

        labSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-logout-24.png"))); // NOI18N
        labSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labSairMouseClicked(evt);
            }
        });

        jLabel2.setText("Sair");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHeaderLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(labSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo)
                    .addComponent(lblSubtitulo))
                .addGap(25, 25, 25))
        );

        pnlContent.setDividerLocation(200);
        pnlContent.setDividerSize(0);

        pnlLeftSide.setBackground(new java.awt.Color(102, 10, 23));
        pnlLeftSide.setToolTipText("");

        btnCardapio.setBackground(new java.awt.Color(102, 10, 23));
        btnCardapio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnCardapio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hamburguer-24.png"))); // NOI18N
        btnCardapio.setText("Ver Cardapio");
        btnCardapio.setBorderPainted(false);
        btnCardapio.setFocusPainted(false);
        btnCardapio.setFocusable(false);
        btnCardapio.setMargin(new java.awt.Insets(2, 14, 3, 20));
        btnCardapio.addActionListener(this::btnCardapioActionPerformed);

        btnGerenciamento.setBackground(new java.awt.Color(102, 10, 23));
        btnGerenciamento.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnGerenciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engrenagem-24.png"))); // NOI18N
        btnGerenciamento.setText("Gerenciamento");
        btnGerenciamento.setBorderPainted(false);
        btnGerenciamento.setFocusPainted(false);
        btnGerenciamento.addActionListener(this::btnGerenciamentoActionPerformed);

        btnPerfil.setBackground(new java.awt.Color(102, 10, 23));
        btnPerfil.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-people-24.png"))); // NOI18N
        btnPerfil.setText("Usuarios");
        btnPerfil.setBorderPainted(false);
        btnPerfil.setFocusPainted(false);
        btnPerfil.addActionListener(this::btnPerfilActionPerformed);

        javax.swing.GroupLayout pnlLeftSideLayout = new javax.swing.GroupLayout(pnlLeftSide);
        pnlLeftSide.setLayout(pnlLeftSideLayout);
        pnlLeftSideLayout.setHorizontalGroup(
            pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCardapio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGerenciamento, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlLeftSideLayout.setVerticalGroup(
            pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        pnlContent.setLeftComponent(pnlLeftSide);

        pnlRightSide.setBackground(new java.awt.Color(220, 220, 220));

        javax.swing.GroupLayout pnlRightSideLayout = new javax.swing.GroupLayout(pnlRightSide);
        pnlRightSide.setLayout(pnlRightSideLayout);
        pnlRightSideLayout.setHorizontalGroup(
            pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        pnlRightSideLayout.setVerticalGroup(
            pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        pnlContent.setRightComponent(pnlRightSide);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlContent, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardapioActionPerformed
        card.show(pnlRightSide, "Cardapio");
    }//GEN-LAST:event_btnCardapioActionPerformed

    private void btnGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciamentoActionPerformed
        card.show(pnlRightSide, "Gerenciamento");
    }//GEN-LAST:event_btnGerenciamentoActionPerformed

    private void labSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labSairMouseClicked
        this.dispose();
        new Login().setVisible(true);

    }//GEN-LAST:event_labSairMouseClicked

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        card.show(pnlRightSide,"Perfil");
    }//GEN-LAST:event_btnPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnCardapio;
    private javax.swing.JButton btnGerenciamento;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel labSair;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JSplitPane pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlLeftSide;
    private javax.swing.JPanel pnlRightSide;
    // End of variables declaration//GEN-END:variables
}
