/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.astaxdev.cardapio.view.gerenciamento;

import com.astaxdev.cardapio.model.TipoUsuario;
import com.astaxdev.cardapio.model.Usuario;
import com.astaxdev.cardapio.util.BancoDeDados;
import com.astaxdev.cardapio.view.Cadastro;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author astaxgg
 */
public class TelaPerfil extends javax.swing.JPanel {
    private int posicaoTabela = -1;                    
    private int id = 0;
    private BancoDeDados banco = BancoDeDados.getInstance();
    
    public TelaPerfil() {
        initComponents();
        atualizarTabela();
        btnDeletar.setEnabled(false);
        btnSalvar.setEnabled(false);
        cbxCargo.setEnabled(false);
        txtNome.setEnabled(false);
        pswSenha.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        pnlConteudo = new javax.swing.JPanel();
        sclTabela = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnDeletar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        cbxCargo = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        pswSenha = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(220, 220, 220));

        pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeader.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(15, 15, 15));
        lblTitulo.setText("Gerenciamento de usuários");

        lblSubtitulo.setForeground(new java.awt.Color(15, 15, 15));
        lblSubtitulo.setText("Gerencie os usuários do sistema");

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-people-24.png"))); // NOI18N

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlConteudo.setBackground(new java.awt.Color(255, 255, 255));
        pnlConteudo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        pnlConteudo.setForeground(new java.awt.Color(255, 255, 255));
        pnlConteudo.setFocusable(false);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nome", "Perfil"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        sclTabela.setViewportView(tblUsuarios);

        btnDeletar.setBackground(new java.awt.Color(144, 38, 53));
        btnDeletar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("Deletar");
        btnDeletar.setBorderPainted(false);
        btnDeletar.setFocusPainted(false);
        btnDeletar.addActionListener(this::btnDeletarActionPerformed);

        btnSalvar.setBackground(new java.awt.Color(102, 10, 23));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setBorderPainted(false);
        btnSalvar.setFocusPainted(false);
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        txtNome.setText("Nome");

        cbxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Administrador", "Normal" }));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(15, 15, 15));
        lblNome.setText("Nome");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(15, 15, 15));
        lblSenha.setText("Senha Nova");

        lblCargo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(15, 15, 15));
        lblCargo.setText("Cargo");

        pswSenha.setText("jPasswordField1");
        pswSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswSenhaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlConteudoLayout = new javax.swing.GroupLayout(pnlConteudo);
        pnlConteudo.setLayout(pnlConteudoLayout);
        pnlConteudoLayout.setHorizontalGroup(
            pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConteudoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sclTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addGroup(pnlConteudoLayout.createSequentialGroup()
                        .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlConteudoLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(71, 71, 71)
                                .addComponent(lblSenha))
                            .addGroup(pnlConteudoLayout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlConteudoLayout.createSequentialGroup()
                                .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeletar)
                                .addGap(2, 2, 2))
                            .addGroup(pnlConteudoLayout.createSequentialGroup()
                                .addComponent(lblCargo)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlConteudoLayout.setVerticalGroup(
            pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConteudoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblSenha)
                    .addComponent(lblCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar)
                    .addComponent(btnDeletar)
                    .addComponent(pswSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sclTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        posicaoTabela = tblUsuarios.getSelectedRow();    
        btnDeletar.setEnabled(true);
        btnSalvar.setEnabled(true);
        id = (int) tblUsuarios.getValueAt(posicaoTabela, 0);
        preencherCampos(id);
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        for (Usuario u : banco.getUsuarios()){
            if(u.getId() == id){
                if (u.getId() == banco.getSessao().getId()) {
                    JOptionPane.showMessageDialog(this, "Você não pode deletar o seu proprio cadastro!");
                    break;
                }
                
                banco.getUsuarios().remove(u);
                limparCampos();
                
                break;
            }
        }    
        
        id = 0;
        posicaoTabela = -1;
        atualizarTabela();
        btnDeletar.setEnabled(false);
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        for (Usuario u : banco.getUsuarios()){
            if(u.getId() == id){
                if (u.getId() == banco.getSessao().getId()) {
                    JOptionPane.showMessageDialog(this, "Você não pode alterar o seu proprio cadastro!");
                    break;
                }
                
                String senha = String.valueOf(pswSenha.getPassword());
                u.setPerfil(cbxCargo.getSelectedItem() == "Administrador" ? TipoUsuario.ADMINISTRADOR : TipoUsuario.PADRAO);
                u.setUsername(txtNome.getText());
                u.setSenha(senha);
                limparCampos();
                
                break;
            }
        }  
        
        atualizarTabela();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void pswSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswSenhaFocusGained
        pswSenha.setEchoChar((char)0);
    }//GEN-LAST:event_pswSenhaFocusGained

    private void pswSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswSenhaFocusLost
        pswSenha.setEchoChar('*');
    }//GEN-LAST:event_pswSenhaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCargo;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlConteudo;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JScrollPane sclTabela;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela(){
        DefaultTableModel tabelaUSuarios = (DefaultTableModel) tblUsuarios.getModel(); 
        tabelaUSuarios.setRowCount(0);

        for (Usuario u : banco.getUsuarios()){
            tabelaUSuarios.addRow(new Object[]{
                u.getId(),          
                u.getUsername(),    
                u.getPerfil() == TipoUsuario.ADMINISTRADOR ? "Admin" : "Normal"     
            });
        }

        tabelaUSuarios.fireTableDataChanged();
    }
    
    private void limparCampos() {
        cbxCargo.setSelectedIndex(0);
        txtNome.setText("Nome");
        pswSenha.setText("Senha");
        
        cbxCargo.setEnabled(false);
        txtNome.setEnabled(false);
        pswSenha.setEnabled(false);
    }
    
    private void preencherCampos(int id) {
        for (Usuario u : banco.getUsuarios()){
            if(u.getId() == id){
                cbxCargo.setSelectedItem(u.getPerfil() == TipoUsuario.ADMINISTRADOR ? "Administrador" : "Normal");
                txtNome.setText(u.getUsername());
                pswSenha.setText(u.getSenha());
                break;
            }
        }  
        
        cbxCargo.setEnabled(true);
        txtNome.setEnabled(true);
        pswSenha.setEnabled(true);
    }
}
