/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.astaxdev.cardapio.view.cardapio;

import com.astaxdev.cardapio.model.Categoria;
import com.astaxdev.cardapio.model.Item;
import com.astaxdev.cardapio.view.cardapio.item.ItemCardapio;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Box;

/**
 *
 * @author astaxgg
 */
public class TelaCardapio extends javax.swing.JPanel {
    private List<Item> itens;
    /**
     * Creates new form Cardapio
     */
    public TelaCardapio() {
        initComponents();
        
        this.itens = new ArrayList<>();
        itens.add(new Item("Hambúrguer Artesanal", "Pão brioche.", 35.50, Categoria.LANCHE));
        itens.add(new Item("Batata Frita Especial", "Batata rústica.", 22.00, Categoria.PORCAO));
        itens.add(new Item("Soda Italiana", "Sabor maçã verde.", 12.00, Categoria.BEBIDA));
        itens.add(new Item("Pudim de Leite", "Receita tradicional.", 15.00, Categoria.SOBREMESA));
        
        renderizarItens("");
    }
    
    public void renderizarItens(String filtro) {
        pnlRaiz.removeAll();
        
        for (Item i : itens) {
            ItemCardapio novo = new ItemCardapio();
            String nome = i.getNome();
            
            if (nome.toLowerCase().contains(filtro.toLowerCase())) { // melhorar, isso não pega acento | pao ~= pão
                novo.setNome(nome);
                novo.setAlignmentX(Component.LEFT_ALIGNMENT);
                novo.setDescricao(i.getDescricao());
                novo.setPreco(i.getPreco());
                novo.setIcone(i.getIcone());
            
                pnlRaiz.add(novo);
                pnlRaiz.add(Box.createVerticalStrut(8));
            }
        }
        
        pnlRaiz.revalidate();
        pnlRaiz.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPesquisar = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        sclCardapio = new javax.swing.JScrollPane();
        pnlRaiz = new javax.swing.JPanel();

        setBackground(new java.awt.Color(220, 220, 220));
        setPreferredSize(new java.awt.Dimension(621, 470));

        txtPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        txtPesquisar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtPesquisar.setForeground(new java.awt.Color(51, 51, 51));
        txtPesquisar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPesquisar.setText("Pesquisar...");
        txtPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        txtPesquisar.setSelectionColor(new java.awt.Color(152, 60, 73));
        txtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisarFocusLost(evt);
            }
        });
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(20, 20, 20));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pesquisar-24.png"))); // NOI18N
        lblTitulo.setText("Pesquisar Item");

        sclCardapio.setBorder(null);
        sclCardapio.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlRaiz.setBackground(new java.awt.Color(220, 220, 220));
        pnlRaiz.setLayout(new javax.swing.BoxLayout(pnlRaiz, javax.swing.BoxLayout.Y_AXIS));
        sclCardapio.setViewportView(pnlRaiz);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                    .addComponent(sclCardapio))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sclCardapio, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        renderizarItens(txtPesquisar.getText());
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void txtPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarFocusGained
        if (txtPesquisar.getText().equals("Pesquisar...")) {
            txtPesquisar.setText("");
        }
    }//GEN-LAST:event_txtPesquisarFocusGained

    private void txtPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisarFocusLost
        if (txtPesquisar.getText().isEmpty()) {
            txtPesquisar.setText("Pesquisar...");
        }
    }//GEN-LAST:event_txtPesquisarFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlRaiz;
    private javax.swing.JScrollPane sclCardapio;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
