/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.astaxdev.cardapio.view.pedido;

import com.astaxdev.cardapio.model.Categoria;
import com.astaxdev.cardapio.model.Item;
import com.astaxdev.cardapio.model.Pedido;
import com.astaxdev.cardapio.model.Usuario;
import com.astaxdev.cardapio.util.BancoDeDados;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author astaxgg
 */
public class TelaPedido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPedido.class.getName());
    private BancoDeDados banco = BancoDeDados.getInstance();
    private Item combo;
    private List<String> ingredientes;
    
    /**
     * Creates new form TelaPedido
     */
    public TelaPedido() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        
        habilitarCampos(true);
        lblPreco.setText("R$" + String.format("%.2f", 100.00));
        lblTitulo.setText(lblTitulo.getText().replace("{TipoPedido}", "Customizado"));
    }
    
    public TelaPedido(Item combo) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        
        this.combo = combo;
        habilitarCampos(false);
        marcarIngredientes(combo.getIngredientes());
        lblPreco.setText("R$" + String.format("%.2f", combo.getPreco()));
        lblTitulo.setText(lblTitulo.getText().replace("{TipoPedido}", combo.getNome())); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        pnlIngredientes = new javax.swing.JPanel();
        lblTituloIngrediente = new javax.swing.JLabel();
        chkHbgArtesanal = new javax.swing.JCheckBox();
        chkHbgAmericano = new javax.swing.JCheckBox();
        chhCoca2l = new javax.swing.JCheckBox();
        chkCoca600ml = new javax.swing.JCheckBox();
        chkBatataEspecial = new javax.swing.JCheckBox();
        chkBatata = new javax.swing.JCheckBox();
        chkCalabresaAcb = new javax.swing.JCheckBox();
        chkFrangoPss = new javax.swing.JCheckBox();
        chkBoloChoco = new javax.swing.JCheckBox();
        chkSorvete = new javax.swing.JCheckBox();
        chkChantilly = new javax.swing.JCheckBox();
        chkPudim = new javax.swing.JCheckBox();
        pnlHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlEndereco = new javax.swing.JPanel();
        lblTituloIngrediente1 = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        sclExtras = new javax.swing.JScrollPane();
        txaExtras = new javax.swing.JTextArea();
        btnPedido = new javax.swing.JButton();
        lblPreco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(220, 220, 220));

        pnlIngredientes.setBackground(new java.awt.Color(225, 225, 225));
        pnlIngredientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblTituloIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloIngrediente.setForeground(new java.awt.Color(30, 30, 30));
        lblTituloIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ingredientes-22.png"))); // NOI18N
        lblTituloIngrediente.setText("Ingredientes");

        chkHbgArtesanal.setForeground(new java.awt.Color(30, 30, 30));
        chkHbgArtesanal.setText("Hamburguer Artesanal");

        chkHbgAmericano.setForeground(new java.awt.Color(30, 30, 30));
        chkHbgAmericano.setText("Hamburguer Americano");

        chhCoca2l.setForeground(new java.awt.Color(30, 30, 30));
        chhCoca2l.setText("CocaCola 2l");

        chkCoca600ml.setForeground(new java.awt.Color(30, 30, 30));
        chkCoca600ml.setText("CocaCola 600ml");

        chkBatataEspecial.setForeground(new java.awt.Color(30, 30, 30));
        chkBatataEspecial.setText("Batata Frita Especial");

        chkBatata.setForeground(new java.awt.Color(30, 30, 30));
        chkBatata.setText("Batata Frita");

        chkCalabresaAcb.setForeground(new java.awt.Color(30, 30, 30));
        chkCalabresaAcb.setText("Calabresa Acebolada");

        chkFrangoPss.setForeground(new java.awt.Color(30, 30, 30));
        chkFrangoPss.setText("Frango a Passarinho");

        chkBoloChoco.setForeground(new java.awt.Color(30, 30, 30));
        chkBoloChoco.setText("Bolo de Chocolate");

        chkSorvete.setForeground(new java.awt.Color(30, 30, 30));
        chkSorvete.setText("Bola de Sorvete");

        chkChantilly.setForeground(new java.awt.Color(30, 30, 30));
        chkChantilly.setText("Chantilly");

        chkPudim.setForeground(new java.awt.Color(30, 30, 30));
        chkPudim.setText("Pudim");

        javax.swing.GroupLayout pnlIngredientesLayout = new javax.swing.GroupLayout(pnlIngredientes);
        pnlIngredientes.setLayout(pnlIngredientesLayout);
        pnlIngredientesLayout.setHorizontalGroup(
            pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngredientesLayout.createSequentialGroup()
                        .addComponent(lblTituloIngrediente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlIngredientesLayout.createSequentialGroup()
                        .addGroup(pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkHbgArtesanal)
                            .addComponent(chkHbgAmericano)
                            .addComponent(chhCoca2l)
                            .addComponent(chkCoca600ml))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkBatataEspecial)
                            .addComponent(chkFrangoPss)
                            .addComponent(chkCalabresaAcb)
                            .addComponent(chkBatata))
                        .addGap(57, 57, 57)
                        .addGroup(pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkSorvete)
                            .addComponent(chkBoloChoco)
                            .addComponent(chkChantilly)
                            .addComponent(chkPudim))
                        .addGap(14, 14, 14))))
        );
        pnlIngredientesLayout.setVerticalGroup(
            pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloIngrediente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHbgArtesanal)
                    .addComponent(chkBatataEspecial)
                    .addComponent(chkBoloChoco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkHbgAmericano)
                    .addComponent(chkBatata)
                    .addComponent(chkSorvete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chhCoca2l)
                    .addComponent(chkCalabresaAcb)
                    .addComponent(chkChantilly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCoca600ml)
                    .addComponent(chkFrangoPss)
                    .addComponent(chkPudim))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pnlHeader.setBackground(new java.awt.Color(123, 16, 32));

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(220, 220, 220));
        lblTitulo.setText("Pedido {TipoPedido}");

        lblSubtitulo.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(220, 220, 220));
        lblSubtitulo.setText("Gerencie seu pedido");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante-48.png"))); // NOI18N

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtitulo)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo)
                    .addComponent(lblSubtitulo)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlHeaderLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pnlEndereco.setBackground(new java.awt.Color(225, 225, 225));
        pnlEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblTituloIngrediente1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloIngrediente1.setForeground(new java.awt.Color(30, 30, 30));
        lblTituloIngrediente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/endereço-22.png"))); // NOI18N
        lblTituloIngrediente1.setText("Informações Extras");

        lblDesc.setForeground(new java.awt.Color(30, 30, 30));
        lblDesc.setText("Descrição Extra (Não obrigatorio)");

        txaExtras.setBackground(new java.awt.Color(180, 180, 180));
        txaExtras.setColumns(20);
        txaExtras.setRows(5);
        sclExtras.setViewportView(txaExtras);

        javax.swing.GroupLayout pnlEnderecoLayout = new javax.swing.GroupLayout(pnlEndereco);
        pnlEndereco.setLayout(pnlEnderecoLayout);
        pnlEnderecoLayout.setHorizontalGroup(
            pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sclExtras)
                    .addGroup(pnlEnderecoLayout.createSequentialGroup()
                        .addGroup(pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblDesc))
                            .addComponent(lblTituloIngrediente1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlEnderecoLayout.setVerticalGroup(
            pnlEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloIngrediente1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sclExtras)
                .addContainerGap())
        );

        btnPedido.setBackground(new java.awt.Color(123, 16, 32));
        btnPedido.setForeground(new java.awt.Color(220, 220, 220));
        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pedido-20.png"))); // NOI18N
        btnPedido.setText("Finalizar Pedido");
        btnPedido.setBorderPainted(false);
        btnPedido.setFocusPainted(false);
        btnPedido.addActionListener(this::btnPedidoActionPerformed);

        lblPreco.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPreco.setForeground(new java.awt.Color(123, 16, 32));
        lblPreco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPreco.setText("R$00,00");

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlIngredientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(lblPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        Item combo = this.combo;
        Pedido pedido;

        if (combo != null) {
            String mesa = javax.swing.JOptionPane.showInputDialog(this, "Digite o número da mesa:");    
            pedido = new Pedido(txaExtras.getText(), mesa, this.combo, banco.getSessao());
        } else {
            pedido = retornaPedido();
        }
        
        this.dispose();
        new TelaRecibo(pedido).setVisible(true);
    }//GEN-LAST:event_btnPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPedido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chhCoca2l;
    private javax.swing.JCheckBox chkBatata;
    private javax.swing.JCheckBox chkBatataEspecial;
    private javax.swing.JCheckBox chkBoloChoco;
    private javax.swing.JCheckBox chkCalabresaAcb;
    private javax.swing.JCheckBox chkChantilly;
    private javax.swing.JCheckBox chkCoca600ml;
    private javax.swing.JCheckBox chkFrangoPss;
    private javax.swing.JCheckBox chkHbgAmericano;
    private javax.swing.JCheckBox chkHbgArtesanal;
    private javax.swing.JCheckBox chkPudim;
    private javax.swing.JCheckBox chkSorvete;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloIngrediente;
    private javax.swing.JLabel lblTituloIngrediente1;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlEndereco;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlIngredientes;
    private javax.swing.JScrollPane sclExtras;
    private javax.swing.JTextArea txaExtras;
    // End of variables declaration//GEN-END:variables
    
    private Pedido retornaPedido(){
        String mesa = javax.swing.JOptionPane.showInputDialog(this, "Digite o número da mesa:");        
        String infoExtras = txaExtras.getText();
        
        Item combo = new Item("Customizado", infoExtras, 12.00, pegarIngredientes(), Categoria.PORCAO);
        return new Pedido("Customizado", mesa, combo, banco.getSessao());
    }
    
    private List<String> pegarIngredientes() {
        List<String> ingredientes = new ArrayList<>();

        if (chhCoca2l.isSelected()) {
            ingredientes.add("CocaCola 2l");
        }
        
        if (chkBatata.isSelected()) {
            ingredientes.add("Batata Frita");
        }
        
        if (chkBatataEspecial.isSelected()) {
            ingredientes.add("Batata Especial");
        }
        
        if (chkBoloChoco.isSelected()) {
            ingredientes.add("Bolo de Chocolate");
        }
        
        if (chkCalabresaAcb.isSelected()) {
            ingredientes.add("Calabresa");
        }
        
        if (chkChantilly.isSelected()) {
            ingredientes.add("Chantilly");
        }
        
        if (chkCoca600ml.isSelected()) {
            ingredientes.add("CocaCola 600ml");
        }
        
        if (chkFrangoPss.isSelected()) {
            ingredientes.add("Frango");
        }
        
        if (chkHbgAmericano.isSelected()) {
            ingredientes.add("Hamburguer Americano");
        }
        
        if (chkHbgArtesanal.isSelected()) {
            ingredientes.add("Hamburguer Artesanal");
        }
        
        if (chkPudim.isSelected()) {
            ingredientes.add("Pudim");
        }
        
        if (chkSorvete.isSelected()) {
            ingredientes.add("Sorvete");
        }

        return ingredientes;
    }
    
    private void habilitarCampos(boolean ativo) {
        chhCoca2l.setEnabled(ativo);
        chkBatata.setEnabled(ativo);
        chkBatataEspecial.setEnabled(ativo);
        chkBoloChoco.setEnabled(ativo);
        chkCalabresaAcb.setEnabled(ativo);
        chkChantilly.setEnabled(ativo);
        chkCoca600ml.setEnabled(ativo);
        chkFrangoPss.setEnabled(ativo);
        chkHbgAmericano.setEnabled(ativo);
        chkHbgArtesanal.setEnabled(ativo);
        chkPudim.setEnabled(ativo);
        chkSorvete.setEnabled(ativo);
    }
    
    private void marcarIngredientes(List<String> i) {
        desmarcarIngredientes();
        
        if (i.contains("CocaCola 2l")) {
            chhCoca2l.setSelected(true);
        }
        
        if (i.contains("Batata Frita")) {
            chkBatata.setSelected(true);
        }
        
        if (i.contains("Batata Especial")) {
            chkBatataEspecial.setSelected(true);
        }
        
        if (i.contains("Bolo de Chocolate")) {
            chkBoloChoco.setSelected(true);
        }
        
        if (i.contains("Calabresa")) {
            chkCalabresaAcb.setSelected(true);
        }
        
        if (i.contains("Chantilly")) {
            chkChantilly.setSelected(true);
        }
        
        if (i.contains("CocaCola 600ml")) {
            chkCoca600ml.setSelected(true);
        }
        
        if (i.contains("Frango")) {
            chkFrangoPss.setSelected(true);
        }
        
        if (i.contains("Hamburguer Americano")) {
            chkHbgAmericano.setSelected(true);
        }
        
        if (i.contains("Hamburguer Artesanal")) {
            chkHbgArtesanal.setSelected(true);
        }
        
        if (i.contains("Pudim")) {
            chkPudim.setSelected(true);
        }
        
        if (i.contains("Sorvete")) {
            chkSorvete.setSelected(true);
        }
    }
    
    private void desmarcarIngredientes() {
        chhCoca2l.setSelected(false);
        chkBatata.setSelected(false);
        chkBatataEspecial.setSelected(false);
        chkBoloChoco.setSelected(false);
        chkCalabresaAcb.setSelected(false);
        chkChantilly.setSelected(false);
        chkCoca600ml.setSelected(false);
        chkFrangoPss.setSelected(false);
        chkHbgAmericano.setSelected(false);
        chkHbgArtesanal.setSelected(false);
        chkPudim.setSelected(false);
        chkSorvete.setSelected(false);
    }
}
